name: gal
description: Gal is a Flutter plugin for saving image/video to gallary app. You can also easily handle permissions.
version: 1.8.5
homepage: https://pub.dev/packages/gal
repository: https://github.com/natsuk4ze/gal

topics:
 - gallery
 - video
 - image
 - photos
 - util

screenshots:
 - description: 'Screenshot of example app in Android.'
   path: example/assets/android_example.gif
 - description: 'Screenshot of example app in iOS.'
   path: example/assets/ios_example.gif

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: studio.midoridesign.gal
        pluginClass: GalPlugin
      ios:
        pluginClass: GalPlugin
