name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '0 0 * * *'

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  issues: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'natsuk4ze/gal' }}
    steps:
      - uses: godofredoc/no-response@0ce2dc0e63e1c7d2b87752ceed091f6d32c9df09
        with:
          token: ${{ github.token }}
          closeComment: >
            Without additional information, we are unfortunately not sure how to
            resolve this issue. We are therefore reluctantly going to close this
            bug for now.

            If you find this problem please file a new issue with the same description,
            Thanks for your contribution.
          daysUntilClose: 20
          responseRequiredLabel: "ðŸ’¬ waiting for response"
